pipeline {
    agent any
    tools {
        maven 'maven_3_8_1'
        jdk 'jdk_17' // Asumiendo que estás usando Java 17, asegúrate de que este nombre coincida con tu configuración de Jenkins
    }
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            steps {
                dir('backend') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('backend') {
                    bat 'mvn test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    bat 'docker build -t haruhisomu/backend:latest .'
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerPass', variable: 'DOCKER_HUB_PASSWORD')]) {
                    bat 'docker login -u haruhisomu -p %DOCKER_HUB_PASSWORD%'
                }
                bat 'docker push haruhisomu/backend:latest'
            }
        }
    }
}
