pipeline {
    agent any
    tools {
        maven 'maven_3_8_1'
    }
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm // Simplificado para usar la configuración del job
            }
        }

        stage('Build Maven') {
            steps {
                script {
                    dir('backend') { // Asegúrate de que el pom.xml esté en esta carpeta
                        bat 'mvn clean package'
                    }
                }
            }
        }

        stage('Unit Tests') {
            steps {
                script {
                    dir('backend') { // Asegúrate de que el pom.xml esté en esta carpeta
                        bat 'mvn test'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('backend') { // Asegúrate de que el Dockerfile esté en esta carpeta
                        bat 'docker build -t haruhisomu/backend:latest .'
                    }
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerPass', variable: 'DOCKER_HUB_PASSWORD')]) {
                        bat 'docker login -u haruhisomu -p %DOCKER_HUB_PASSWORD%'
                    }
                    bat 'docker push haruhisomu/backend:latest'
                }
            }
        }
    }
}
